2025-01-20 14:30:16,108 | INFO | "test_challenge" выполнен успешно
2025-01-20 14:30:16,109 | WARNING | Неверный тип данных для объекта Runner
Имя может быть только строкой, передано int
2025-01-20 14:30:16,109 | WARNING | Traceback (most recent call last):
  File "C:\PycharmProjects\pythonProject3\tests_12_4.py", line 74, in test_run
    runner = Runner(2)
             ^^^^^^^^^
  File "C:\PycharmProjects\pythonProject3\tests_12_4.py", line 15, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int

2025-01-20 14:30:16,110 | WARNING | Неверная скорость для Runner
Скорость не может быть отрицательной, сейчас -5
2025-01-20 14:30:16,138 | WARNING | Traceback (most recent call last):
  File "C:\PycharmProjects\pythonProject3\tests_12_4.py", line 63, in test_walk
    runner = Runner("Вася", -5)
             ^^^^^^^^^^^^^^^^^^
  File "C:\PycharmProjects\pythonProject3\tests_12_4.py", line 20, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5

